---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: accounts.kubesys.io
spec:
  additionalPrinterColumns:
  - JSONPath: .type
    name: type
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: created
    type: string
  group: kubesys.io
  names:
    kind: Account
    plural: accounts
    singular: account
  scope: Namespaced
  version: v1
