---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: regexps.doslab.io
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  group: doslab.io
  names:
    kind: RegExp
    plural: regexps
    shortNames:
    - regexps
    singular: regexp
  scope: Namespaced
  version: v1
