---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: templates.doslab.io
spec:
  additionalPrinterColumns:
    - JSONPath: .type
      name: type
      type: string
  group: doslab.io
  names:
    kind: Template
    plural: templates
    singular: template
  scope: Namespaced
  version: v1
