---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: algs.doslab.io
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    name: created
    type: string
  group: doslab.io
  names:
    kind: Alg
    plural: algs
    singular: alg
  scope: Namespaced
  version: v1
