---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: frontends.doslab.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.type
    name: TYPE
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  group: doslab.io
  names:
    kind: Frontend
    plural: frontends
    shortNames:
    - frontend
    singular: frontend
  scope: Namespaced
  version: v1
