---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: users.doslab.io
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    name: created
    type: string
  group: doslab.io
  names:
    kind: User
    plural: users
    singular: user
  scope: Namespaced
  version: v1
