{
  "apiVersion": "batch/v1beta1",
  "kind": "CronJob",
  "metadata": {
    "name": "busybox",
    "namespace": "default",
    "labels": {
      "app": "busybox"
    }
  },
  "spec": {
    "schedule": "*/1 * * * *",
    "jobTemplate": {
      "spec": {
        "template": {
          "spec": {
            "containers": [
              {
                "image": "busybox",
                "command": [
                  "sleep",
                  "2"
                ],
                "imagePullPolicy": "IfNotPresent",
                "name": "busybox"
              }
            ],
            "restartPolicy": "Never"
          }
        }
      }
    }
  }
}
