{
  "apiVersion": "v1",
  "kind": "ReplicationController",
  "metadata": {
    "name": "busybox",
    "namespace": "default",
    "labels": {
      "app": "busybox"
    }
  },
  "spec": {
    "replicas": 2,
    "template": {
      "metadata": {
        "labels": {
          "app": "busybox"
        }
      },
      "spec": {
        "containers": [
          {
            "image": "busybox",
            "command": [
              "sleep",
              "3600"
            ],
            "imagePullPolicy": "IfNotPresent",
            "name": "busybox"
          }
        ]
      }
    }
  }
}
