{
  "apiVersion": "batch/v1",
  "kind": "Job",
  "metadata": {
    "name": "busybox",
    "namespace": "default",
    "labels": {
      "app": "busybox"
    }
  },
  "spec": {
    "template": {
      "metadata": {
        "labels": {
          "app": "busybox"
        }
      },
      "spec": {
        "containers": [
          {
            "image": "busybox",
            "command": [
              "sleep",
              "2"
            ],
            "imagePullPolicy": "IfNotPresent",
            "name": "busybox"
          }
        ],
        "restartPolicy": "Never"
      }
    }
  }
}
