kind: Service
apiVersion: v1
metadata:
  name: tomcat-service
  namespace: default
spec:
  selector:
    app: tomcat
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
