---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: components.doslab.io
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    name: created
    type: string
  group: doslab.io
  names:
    kind: Component
    plural: components
    singular: component
  scope: Namespaced
  version: v1
