---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mcmfs.doslab.io
spec:
  additionalPrinterColumns:
    - JSONPath: .metadata.creationTimestamp
      name: created
      type: string
  group: doslab.io
  names:
    kind: MCMF
    plural: mcmfs
    singular: mcmf
  scope: Namespaced
  version: v1
