---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: routes.doslab.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.type
    name: TYPE
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  group: doslab.io
  names:
    kind: Route
    plural: routes
    shortNames:
    singular: route
  scope: Namespaced
  version: v1
